---
title: "Análisis de datos proyecto Final de experimentos I"
author: "Daniel Sibaja Salazar"
date: "2024-05-16"
output: pdf_document
---

# Preparación 

```{r}
library(readxl)
base1=read_xlsx("final_registro_cloud.xlsx",col_names = FALSE)
names(base1)=c("Tiempo","BL","Nube","Denied","Right","Solicitudes","ID","Bloque")
base1$BL=as.factor(base1$BL)
base1$Solicitudes=as.factor(base1$Solicitudes)
url=rep(c(1:(nrow(base1)/2)),times=1,each=2)
#base1=cbind(base1,url)
base1$Tiempo=base1$Tiempo*1000



base2=read_xlsx("final_registro_local.xlsx",col_names = FALSE)
names(base2)=c("Tiempo","BL","Nube","Denied","Right","Solicitudes","ID","Bloque")
base2$BL=as.factor(base2$BL)
base2$Solicitudes=as.factor(base2$Solicitudes)
base2$Tiempo=base2$Tiempo*1000

base=rbind(base1,base2)
base$Nube=as.factor(base$Nube)
table(base1$BL,base1$Nube,base1$Solicitudes)
```


```{r}
(table(base1$Bloque))
(table(base2$Bloque))

base=rbind(base1,base2)
base$Nube=as.factor(base$Nube)
table(base$BL,base$Nube,base$Solicitudes)

quitar1=which(base1$Bloque=="N109")
base1=base1[-quitar1,]

quitar2=which(base1$Bloque=="N1009")
base1=base1[-quitar2,]

quitar3=which(base1$Bloque=="N5009")
base1=base1[-quitar3,]

quitar4=which(base1$Bloque=="N5006")
base1=base1[-quitar4,]

quitar5=which(base2$Bloque=="L5006")
base2=base2[-quitar5,]

quitar6=which(base1$Bloque=="N5008")
base1=base1[-quitar6,]

quitar7=which(base2$Bloque=="L5008")
base2=base2[-quitar7,]

quitar8=which(base1$Bloque=="N5004")
base1=base1[-quitar8,]

quitar9=which(base2$Bloque=="L5004")
base2=base2[-quitar9,]

quitar10=which(base1$Bloque=="N1007")
base1=base1[-quitar10,]

quitar11=which(base2$Bloque=="L1007")
base2=base2[-quitar11,]



base=rbind(base1,base2)
base$Nube=as.factor(base$Nube)
table(base$BL,base$Nube,base$Solicitudes)


```
```{r}
library(lme4)

modp1=lmer(Tiempo~Solicitudes*BL*Nube+(1|Bloque),data = base)
drop1(modp1,test = "Chisq")
summary(modp1)

summary(base$Tiempo/1000)
```

Protocolo UDP
Protocolo TCP



$$
\mu_{ijk}=\mu+\alpha_i+\beta_j+\delta_k+(\alpha \beta)_{ij}+(\alpha\delta)_{ik}+(\beta \delta)_{jk}+(\alpha \beta \delta)_{ijk}+\nu_l
$$

