% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={LabUvas},
  pdfauthor={Daniel Sibaja Salazar},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{LabUvas}
\author{Daniel Sibaja Salazar}
\date{}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{preparaciuxf3n}{%
\section{Preparación}\label{preparaciuxf3n}}

\hypertarget{cargar-el-archvio}{%
\subsection{Cargar el archvio}\label{cargar-el-archvio}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{base}\OtherTok{=}\FunctionTok{read.csv}\NormalTok{(}\StringTok{"uvas.csv"}\NormalTok{)}
\NormalTok{base}\SpecialCharTok{$}\NormalTok{localidad}\OtherTok{=}\FunctionTok{factor}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{localidad)}
\end{Highlighting}
\end{Shaded}

\hypertarget{caracteruxedsticas-del-experimento}{%
\subsection{Características del
experimento}\label{caracteruxedsticas-del-experimento}}

No es necesario en este caso, debido a que solo interesa un factor, la
localidad.

\hypertarget{hipuxf3tesis-buxe1sica}{%
\section{Hipótesis básica}\label{hipuxf3tesis-buxe1sica}}

\hypertarget{establezca-la-hipuxf3tesis-buxe1sica-para-verificar-que-en-efecto-las-tres-localidades-no-producen-el-mismo-promedio-de-dulzor.}{%
\subsection{Establezca la hipótesis básica para verificar que en efecto
las tres localidades no producen el mismo promedio de
dulzor.}\label{establezca-la-hipuxf3tesis-buxe1sica-para-verificar-que-en-efecto-las-tres-localidades-no-producen-el-mismo-promedio-de-dulzor.}}

H0: mu1=mu2=m3 H0: t1=t2=t3=0

H1: al menos un par de mus es distinto

\hypertarget{haga-un-boxplot-que-permita-de-una-forma-descriptiva-apoyar-o-contradecir-esta-hipuxf3tesis.}{%
\subsection{Haga un boxplot que permita de una forma descriptiva apoyar
o contradecir esta
hipótesis.}\label{haga-un-boxplot-que-permita-de-una-forma-descriptiva-apoyar-o-contradecir-esta-hipuxf3tesis.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{boxplot}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{brix}\SpecialCharTok{\textasciitilde{}}\NormalTok{base}\SpecialCharTok{$}\NormalTok{localidad)}
\end{Highlighting}
\end{Shaded}

\includegraphics{labuvas_files/figure-latex/unnamed-chunk-2-1.pdf}
Parece que el promedio de Garita es un poco mayor al de Guácima o San
Vito, sin embargo nada luce muy distinto.

\hypertarget{obtenga-las-medias-de-cada-tratamiento.}{%
\subsection{Obtenga las medias de cada
tratamiento.}\label{obtenga-las-medias-de-cada-tratamiento.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m}\OtherTok{=}\FunctionTok{tapply}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{brix,base}\SpecialCharTok{$}\NormalTok{localidad,mean);m}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Garita  Guacima San Vito 
## 16.95526 16.10400 15.97027
\end{verbatim}

\hypertarget{ponga-a-prueba-la-hipuxf3tesis}{%
\subsection{Ponga a prueba la
hipótesis}\label{ponga-a-prueba-la-hipuxf3tesis}}

Automática

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod}\OtherTok{=}\FunctionTok{lm}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{brix}\SpecialCharTok{\textasciitilde{}}\NormalTok{base}\SpecialCharTok{$}\NormalTok{localidad)}
\FunctionTok{anova}\NormalTok{(mod)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Analysis of Variance Table
## 
## Response: base$brix
##                Df  Sum Sq Mean Sq F value   Pr(>F)   
## base$localidad  2  20.691 10.3454  5.7173 0.004496 **
## Residuals      97 175.521  1.8095                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Hay suficiente evidencia estadística para rechazar la hipótesis nula,
aparentemente hay un par de medias distinto.

Paso a paso

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mg}\OtherTok{=}\FunctionTok{mean}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{brix);mg}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 16.378
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{r}\OtherTok{=}\FunctionTok{table}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{localidad)}
\NormalTok{sctrat}\OtherTok{=}\FunctionTok{sum}\NormalTok{(r}\SpecialCharTok{*}\NormalTok{(m}\SpecialCharTok{{-}}\NormalTok{mg)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{cmtrat}\OtherTok{=}\NormalTok{sctrat}\SpecialCharTok{/}\DecValTok{2}\NormalTok{;cmtrat}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 10.34538
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{v}\OtherTok{=}\FunctionTok{tapply}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{brix,base}\SpecialCharTok{$}\NormalTok{localidad,var);v}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Garita  Guacima San Vito 
## 1.983620 1.120400 2.089925
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{scres}\OtherTok{=}\FunctionTok{sum}\NormalTok{((r}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{v);scres}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 175.5208
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cmres}\OtherTok{=}\NormalTok{scres}\SpecialCharTok{/}\NormalTok{(}\FunctionTok{sum}\NormalTok{(r)}\SpecialCharTok{{-}}\DecValTok{3}\NormalTok{);cmres}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.809493
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{f}\OtherTok{=}\NormalTok{cmtrat}\SpecialCharTok{/}\NormalTok{cmres;f}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 5.717279
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{p}\OtherTok{=}\FunctionTok{pf}\NormalTok{(f,}\DecValTok{3{-}1}\NormalTok{,}\DecValTok{100{-}3}\NormalTok{,}\AttributeTok{lower.tail =}\NormalTok{ F);p}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.004495676
\end{verbatim}

El resultado es igual.

\hypertarget{comparaciones-de-los-promedios}{%
\section{Comparaciones de los
promedios}\label{comparaciones-de-los-promedios}}

\hypertarget{dado-que-el-objetivo-es-comparar-todas-las-localidades-entre-suxed-se-trata-de-un-problema-de-comparaciuxf3n-de-todos-los-pares-de-promedios.-escriba-todas-las-hipuxf3tesis-que-se-deben-probar.}{%
\subsection{Dado que el objetivo es comparar todas las localidades entre
sí, se trata de un problema de comparación de todos los pares de
promedios. Escriba todas las hipótesis que se deben
probar.}\label{dado-que-el-objetivo-es-comparar-todas-las-localidades-entre-suxed-se-trata-de-un-problema-de-comparaciuxf3n-de-todos-los-pares-de-promedios.-escriba-todas-las-hipuxf3tesis-que-se-deben-probar.}}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  H0: mu1=mu2
\item
  H0: mu1=mu3
\item
  H0: mu2=mu3
\end{enumerate}

\hypertarget{verifique-que-no-son-ortogonales}{%
\subsection{Verifique que no son
ortogonales}\label{verifique-que-no-son-ortogonales}}

Tengo los siguientes vectores

\begin{itemize}
\tightlist
\item
  (1,-1,0)
\item
  (1,0,-1)
\item
  (0,1,-1)
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{v1}\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{)}
\NormalTok{v2}\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{0}\NormalTok{,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)}
\NormalTok{v3}\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{1}\NormalTok{,}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{)}

\FunctionTok{crossprod}\NormalTok{(v1,v2)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1]
## [1,]    1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{crossprod}\NormalTok{(v1,v3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1]
## [1,]   -1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{crossprod}\NormalTok{(v2,v3)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      [,1]
## [1,]    1
\end{verbatim}

No son ortogonales.

\hypertarget{obtenga-el-cuadrado-medio-residual.}{%
\subsection{Obtenga el cuadrado medio
residual.}\label{obtenga-el-cuadrado-medio-residual.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{v}\OtherTok{=}\FunctionTok{tapply}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{brix,base}\SpecialCharTok{$}\NormalTok{localidad,var)}
\NormalTok{scres}\OtherTok{=}\FunctionTok{sum}\NormalTok{((r}\DecValTok{{-}1}\NormalTok{)}\SpecialCharTok{*}\NormalTok{v)}
\NormalTok{cmres}\OtherTok{=}\NormalTok{scres}\SpecialCharTok{/}\NormalTok{(}\FunctionTok{sum}\NormalTok{(r)}\SpecialCharTok{{-}}\DecValTok{3}\NormalTok{);cmres;}\FunctionTok{anova}\NormalTok{(mod)[}\DecValTok{2}\NormalTok{,}\DecValTok{3}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.809493
\end{verbatim}

\begin{verbatim}
## [1] 1.809493
\end{verbatim}

\hypertarget{obtenga-los-estaduxedsticos-de-interuxe9s-para-realizar-cada-prueba-es-decir-debec-calcular-yiyj}{%
\subsection{Obtenga los estadísticos de interés para realizar cada
prueba, es decir, debec calcular
yi−yj}\label{obtenga-los-estaduxedsticos-de-interuxe9s-para-realizar-cada-prueba-es-decir-debec-calcular-yiyj}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mu1}\OtherTok{=}\NormalTok{m[}\DecValTok{1}\NormalTok{]}
\NormalTok{mu2}\OtherTok{=}\NormalTok{m[}\DecValTok{2}\NormalTok{]}
\NormalTok{mu3}\OtherTok{=}\NormalTok{m[}\DecValTok{3}\NormalTok{]}

\NormalTok{dif1}\OtherTok{=}\FunctionTok{abs}\NormalTok{(mu1}\SpecialCharTok{{-}}\NormalTok{mu2)}
\NormalTok{dif2}\OtherTok{=}\FunctionTok{abs}\NormalTok{(mu1}\SpecialCharTok{{-}}\NormalTok{mu3)}
\NormalTok{dif3}\OtherTok{=}\FunctionTok{abs}\NormalTok{(mu2}\SpecialCharTok{{-}}\NormalTok{mu3)}
\end{Highlighting}
\end{Shaded}

\hypertarget{obtenga-el-error-estuxe1ndar-del-estaduxedstico}{%
\subsection{Obtenga el error estándar del
estadístico}\label{obtenga-el-error-estuxe1ndar-del-estaduxedstico}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ee1}\OtherTok{=}\FunctionTok{sqrt}\NormalTok{(cmres}\SpecialCharTok{*}\NormalTok{((}\DecValTok{1}\SpecialCharTok{/}\NormalTok{r[}\DecValTok{1}\NormalTok{])}\SpecialCharTok{+}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{r[}\DecValTok{2}\NormalTok{])));ee1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Garita 
## 0.3464072
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ee2}\OtherTok{=}\FunctionTok{sqrt}\NormalTok{(cmres}\SpecialCharTok{*}\NormalTok{((}\DecValTok{1}\SpecialCharTok{/}\NormalTok{r[}\DecValTok{1}\NormalTok{])}\SpecialCharTok{+}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{r[}\DecValTok{3}\NormalTok{])));ee2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Garita 
## 0.3106823
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ee3}\OtherTok{=}\FunctionTok{sqrt}\NormalTok{(cmres}\SpecialCharTok{*}\NormalTok{((}\DecValTok{1}\SpecialCharTok{/}\NormalTok{r[}\DecValTok{2}\NormalTok{])}\SpecialCharTok{+}\NormalTok{(}\DecValTok{1}\SpecialCharTok{/}\NormalTok{r[}\DecValTok{3}\NormalTok{])));ee3}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Guacima 
## 0.3482599
\end{verbatim}

\hypertarget{obtenga-el-valor-estandarizado-del-estaduxedstico-dividiuxe9ndolo-por-su-error-estuxe1ndar.}{%
\subsection{Obtenga el valor estandarizado del estadístico dividiéndolo
por su error
estándar.}\label{obtenga-el-valor-estandarizado-del-estaduxedstico-dividiuxe9ndolo-por-su-error-estuxe1ndar.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{est1}\OtherTok{=}\NormalTok{dif1}\SpecialCharTok{/}\NormalTok{ee1}
\NormalTok{est2}\OtherTok{=}\NormalTok{dif2}\SpecialCharTok{/}\NormalTok{ee2}
\NormalTok{est3}\OtherTok{=}\NormalTok{dif3}\SpecialCharTok{/}\NormalTok{ee3}
\end{Highlighting}
\end{Shaded}

\hypertarget{encuentre-la-probabilidad-de-obtener-un-valor-igual-o-mayor-al-estaduxedstico-usando-la-distribuciuxf3n-del-rango-estudentizado-de-tukey.}{%
\subsection{Encuentre la probabilidad de obtener un valor igual o mayor
al estadístico usando la distribución del rango estudentizado de
Tukey.}\label{encuentre-la-probabilidad-de-obtener-un-valor-igual-o-mayor-al-estaduxedstico-usando-la-distribuciuxf3n-del-rango-estudentizado-de-tukey.}}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ptukey}\NormalTok{(est1}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\NormalTok{),}\DecValTok{3}\NormalTok{,}\DecValTok{97}\NormalTok{,}\AttributeTok{lower.tail =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Garita 
## 0.04138099
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ptukey}\NormalTok{(est2}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\NormalTok{),}\DecValTok{3}\NormalTok{,}\DecValTok{97}\NormalTok{,}\AttributeTok{lower.tail =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Garita 
## 0.005730055
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ptukey}\NormalTok{(est3}\SpecialCharTok{*}\FunctionTok{sqrt}\NormalTok{(}\DecValTok{2}\NormalTok{),}\DecValTok{3}\NormalTok{,}\DecValTok{97}\NormalTok{,}\AttributeTok{lower.tail =}\NormalTok{ F)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Guacima 
## 0.9220088
\end{verbatim}

¿como evitar que diga el factor?

\hypertarget{obtenga-estas-probabilidades-automuxe1ticamente-usando-la-funciuxf3n-tukeyhsdmod}{%
\subsection{Obtenga estas probabilidades automáticamente usando la
función
TukeyHSD(mod)}\label{obtenga-estas-probabilidades-automuxe1ticamente-usando-la-funciuxf3n-tukeyhsdmod}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod1}\OtherTok{=}\FunctionTok{aov}\NormalTok{(base}\SpecialCharTok{$}\NormalTok{brix}\SpecialCharTok{\textasciitilde{}}\NormalTok{base}\SpecialCharTok{$}\NormalTok{localidad)}
\FunctionTok{TukeyHSD}\NormalTok{(mod1)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Tukey multiple comparisons of means
##     95% family-wise confidence level
## 
## Fit: aov(formula = base$brix ~ base$localidad)
## 
## $`base$localidad`
##                        diff        lwr         upr     p adj
## Guacima-Garita   -0.8512632 -1.6757890 -0.02673733 0.0413810
## San Vito-Garita  -0.9849929 -1.7244854 -0.24550041 0.0057301
## San Vito-Guacima -0.1337297 -0.9626653  0.69520583 0.9220088
\end{verbatim}

\hypertarget{quuxe9-se-concluye-en-tuxe9rminos-de-las-hipuxf3tesis-que-se-probaron}{%
\subsection{¿Qué se concluye en términos de las hipótesis que se
probaron?}\label{quuxe9-se-concluye-en-tuxe9rminos-de-las-hipuxf3tesis-que-se-probaron}}

Hay suficiente evidencia estadística para rechazar la hipótesis nula de
igualdad de medias en los pares Guacima-Garita y San Vito-Garita, no así
en San vito-guacima.

¿Se puede decir que Garita es el que es distinto?(Como se ve en el
gráfico)

\hypertarget{luxedmites-para-las-diferencias}{%
\section{Límites para las
diferencias}\label{luxedmites-para-las-diferencias}}

\hypertarget{obtenga-intervalos-de-confianza-para-la-diferencia-de-las-medias-solo-en-los-casos-en-que-se-encontruxf3-una-diferencia-significativa.}{%
\subsection{Obtenga intervalos de confianza para la diferencia de las
medias solo en los casos en que se encontró una diferencia
significativa.}\label{obtenga-intervalos-de-confianza-para-la-diferencia-de-las-medias-solo-en-los-casos-en-que-se-encontruxf3-una-diferencia-significativa.}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{dif1;dif2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Garita 
## 0.8512632
\end{verbatim}

\begin{verbatim}
##    Garita 
## 0.9849929
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{t}\OtherTok{=}\FunctionTok{qt}\NormalTok{(}\DecValTok{1}\FloatTok{{-}0.05}\SpecialCharTok{/}\NormalTok{(}\DecValTok{2}\SpecialCharTok{*}\DecValTok{2}\NormalTok{),}\DecValTok{97}\NormalTok{);t}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.276728
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ic1}\OtherTok{=}\FunctionTok{c}\NormalTok{(dif1}\SpecialCharTok{{-}}\NormalTok{t}\SpecialCharTok{*}\NormalTok{ee1,dif1}\SpecialCharTok{+}\NormalTok{t}\SpecialCharTok{*}\NormalTok{ee1);ic1}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##     Garita     Garita 
## 0.06258823 1.63993809
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{ic2}\OtherTok{=}\FunctionTok{c}\NormalTok{(dif2}\SpecialCharTok{{-}}\NormalTok{t}\SpecialCharTok{*}\NormalTok{ee2,dif2}\SpecialCharTok{+}\NormalTok{t}\SpecialCharTok{*}\NormalTok{ee2);ic2}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Garita   Garita 
## 0.277654 1.692332
\end{verbatim}

La diferencia de las medias de Garita y Guacima se espera que esté entre
0.06258823 y 1.63993809

La diferencia de las medias de Garita y San Vito se espera que esté
entre 0.277654 y 1.692332

Con una confianza global del 95\%.

\end{document}
